name: OSMC
description: OSMC library of things
version: 1.2
main: com.osmc.core.MinecraftCore
commands:
  osmc:
    description: OSMC utilities
  smoke:
    description: im so high dude
  hat:
    description: Put a block on your head